export type Episode = {
  number: number;
  slug: string;
  title: string;
  dek: string;
  published: boolean;
  durationSec?: number; // set from the rendered mp4
  music?: { season: string; piece: string };
  concepts?: string[];
  codeAlong?: string[];
  transcript?: string[];
  video?: { mp4: string };
};

export const episodes: Episode[] = [
  {
    number: 1,
    slug: "what-is-henceforth",
    title: "What is Henceforth?",
    dek: "A calculator you can teach — that also writes Bitcoin.",
    published: true,
    durationSec: 98,
    music: { season: "Spring", piece: "Vivaldi · Allegro (RV 269 i)" },
    concepts: [
      "FORTH is a calculator you talk to in postfix: 2 3 + .",
      "You can teach it new words — : double 2 * ; — then reuse them.",
      "The same machine writes Bitcoin Script, and a payment reads like a sentence.",
    ],
    // Curated to commands that run on a fresh install — tutorial-only lesson
    // words (program-intro, henceforth?) are excluded; a new app hasn't defined them.
    codeAlong: [
      "2 3 +",
      ".",
      ": double  2 * ;",
      "21 double .",
      "SCRIPT-BEGIN",
      "OP_DUP OP_HASH160 OP_EQUALVERIFY OP_CHECKSIG",
      "SCRIPT-END",
      ': pay-rent  1000 s" 1Q88RPbgtGfaDvQYd9Yx3UC86vAhcDSjob" send ;',
    ],
    transcript: [
      "so — what IS this thing?",
      "watch. it answers by doing.",
      "give it two numbers… and +.",
      "it added them. it's a calculator.",
      "but here's the good part —",
      "i just taught it a word.",
      "double means times two.",
      "see that? it knows double now.",
      "words you make. that's the idea.",
      "now… the other half.",
      "same prompt. watch closely.",
      "these are bitcoin words.",
      "that's the shape of a coin-lock.",
      "same machine. just more words.",
      "one last word — read it slow.",
      "pay rent: send 1000 there.",
      "it reads like a sentence.",
      "and it's also a payment.",
      "that's henceforth.",
      "one prompt. you teach it. let's go.",
    ],
    video: { mp4: "/learn/what-is-henceforth/episode.mp4" },
  },
  {
    number: 2,
    slug: "the-stack",
    title: "The Stack",
    dek: "Numbers live in a pile — newest on top, newest off first.",
    published: true,
    durationSec: 74,
    music: { season: "Summer", piece: "Vivaldi · Presto (RV 315 iii)" },
    concepts: [
      "Numbers pile up on a stack — the newest is always on top.",
      "Operators take from the top: + eats the top two, . prints the top.",
      "Take one too many and you hit underflow — the stack only returns what you put in.",
    ],
    codeAlong: ["3 4 5", "+", "+", ".", "10 20 30", ". . . ."],
    transcript: [
      "but where do the numbers go? onto a pile.",
      "a 3. a 4 on top. a 5 — newest always on top.",
      "that's the stack — a pile of numbers, just waiting.",
      "now watch + eat from it.",
      "+ takes the top two — the 5 and the 4 — and leaves a 9.",
      "again — 3 and 9. now just 12.",
      ". prints the top. there's the 12.",
      "you only ever touch the top.",
      "last on, first off — like a can of tennis balls.",
      "let's empty one right out. three on the pile, 30 on top.",
      "30… 20… 10. empty.",
      "now — one more than we put in. nothing's there.",
      "underflow. you hit the floor — and see, it didn't say ok.",
      "the stack gives back exactly what you put in.",
    ],
    video: { mp4: "/learn/the-stack/episode.mp4" },
  },
  {
    number: 3,
    slug: "backwards-maths",
    title: "Why the maths looks backwards",
    dek: "Postfix, and why the stack is the parentheses.",
    published: true,
    durationSec: 123,
    music: { season: "Autumn", piece: "Vivaldi · Allegro (RV 293 i)" },
    concepts: [
      "You write the numbers first, then the operation — 2 3 + . That's reverse Polish (postfix).",
      "The stack remembers as you go, so 2 3 + 4 * nests without any brackets.",
      "Because the last two numbers already sit on the stack, Fibonacci is one little word: : next-fib  tuck + ;.",
    ],
    codeAlong: [
      "2 3 +",
      ".",
      "2 3 + 4 *",
      ".",
      ": next-fib  tuck + ;",
      "1 1",
      "next-fib .s",
      "next-fib .s",
      "next-fib .s",
      "2drop",
      "2 + 3",
    ],
    transcript: [
      "you already know how to add.",
      "watch how this little machine wants it.",
      "you put the numbers down first —",
      "two, then three.",
      "then you say: add.",
      "five. the plus reached back and grabbed the two.",
      "numbers first, then the operation —",
      "that's reverse polish.",
      "and it stacks up — no brackets.",
      "two plus three is five —",
      "then five times four.",
      "twenty. the stack just remembers.",
      "now — one that's a headache in most languages.",
      "the fibonacci numbers — each one the last two, added.",
      "python needs a loop and two boxes to hold them.",
      "but our two numbers already sit on the stack.",
      "so it's one little word.",
      "take the pair, make the next one.",
      "start it with two ones.",
      "now nudge it forward — again and again.",
      "and it just keeps climbing —",
      "a hundred and forty-four — the twelfth.",
      "fibonacci. in one little word.",
      "clear the pair —",
      "and the school way? watch it break.",
      "no — the plus went looking for two numbers,",
      "and found nothing behind it.",
      "numbers first. that's the whole trick.",
      "henceforth.",
    ],
    video: { mp4: "/learn/backwards-maths/episode.mp4" },
  },
  {
    number: 4,
    slug: "words-from-words",
    title: "Words from words",
    dek: "Words made from words — all the way down to a payment.",
    published: true,
    durationSec: 113,
    music: { season: "Winter", piece: "Vivaldi · Allegro (RV 297 i)" },
    concepts: [
      "A colon definition teaches a new word: : double  2 * ; — then it's yours, used like any built-in.",
      "Bigger words are built from the small ones — quadruple is double double, square is dup *, cube is dup square *. Factoring, all the way down.",
      "Mistype a word and Henceforth points you home with a did you mean? hint — and a payment, : pay-rent … send ;, is defined the exact same way.",
    ],
    // Every word here is defined inline, so the whole lesson runs on a fresh
    // install. squre is the deliberate typo that triggers the did-you-mean hint.
    codeAlong: [
      ": double  2 * ;",
      "21 double .",
      "see double",
      ": quadruple  double double ;",
      "5 quadruple .",
      ": square  dup * ;",
      "7 square .",
      ": cube  dup square * ;",
      "3 cube .",
      "squre",
      ': pay-rent  1000 s" 1Q88RPbgtGfaDvQYd9Yx3UC86vAhcDSjob" send ;',
    ],
    transcript: [
      "last time — small words made big maths.",
      "but where do the small words come from?",
      "you make them. watch.",
      "double. you taught it this — episode one.",
      "still here. yours, and built-in, all at once.",
      "and you can look inside. there's its recipe.",
      "now — a bigger word, from the one you made.",
      "quadruple. just double — twice.",
      "twenty. a word, standing on a word.",
      "what if a word needs its number twice?",
      "you copy the top. that's dup.",
      "dup copies it — then times itself.",
      "forty-nine. seven, squared.",
      "cube stands on square — square stands on dup.",
      "small words. all the way down.",
      "and a word you never taught it?",
      "no — it only knows the words you made.",
      "but see — it points you home.",
      "one more. remember this — from episode one?",
      "that bitcoin word? it was a word i defined.",
      "same colon. same semicolon. same : ... ;",
      "a payment is just another word you teach.",
      "henceforth.",
    ],
    video: { mp4: "/learn/words-from-words/episode.mp4" },
  },
  {
    number: 5,
    slug: "moving-numbers",
    title: "Moving numbers",
    dek: "The shuffle words change where numbers sit — never what they are.",
    published: true,
    durationSec: 95,
    music: { season: "Bach", piece: "Brandenburg No. 3 · Allegro (BWV 1048 i)" },
    concepts: [
      "The stack only ever hands you its top — so to use a number twice, in a new order, or from underneath, you reach for a mover: dup, swap, over, rot, drop.",
      "Movers change where numbers sit, never what they are. swap flips the top two, so 10 4 swap - leaves 4 - 10 = -6 — same numbers, new order.",
      "A mover still needs operands — swap on a one-item stack hits the floor (underflow). Bitcoin Script has the same move, OP_DUP, which you'll wield in episode ten.",
    ],
    // Every command is typed live at the prompt, so the whole lesson runs on a
    // fresh install. The final bare swap is the deliberate underflow.
    codeAlong: [
      "7 dup .s",
      "2drop",
      "10 4 .s",
      "swap .s",
      "- .",
      "1 2 over .s",
      "2drop drop",
      "1 2 3 rot .s",
      "2drop drop",
      "7 8 drop .s",
      "swap",
    ],
    transcript: [
      "last time — you copied the top.",
      "that was dup. it made square.",
      "dup's got a family — words that just move numbers.",
      "because the stack only ever hands you the top.",
      "dup — copy the top. you've met this one.",
      "what if they're backwards?",
      "i want 4 minus 10 — but 4's on top.",
      "swap — flip the top two.",
      "minus six. same numbers, new order.",
      "and the one underneath?",
      "over — copy the second one up top.",
      "buried deeper?",
      "rot — bring the bottom one up.",
      "and when you don't need it?",
      "drop — throw the top away. pretty simple, huh?",
      "but they still need numbers to move.",
      "give swap one — it hits the floor.",
      "movers need a stocked stack.",
      "watch — none of them did math.",
      "they only move numbers. never change what they are.",
      "bitcoin has this same move — op_dup.",
      "you'll wield it in episode ten.",
      "henceforth.",
    ],
    video: { mp4: "/learn/moving-numbers/episode.mp4" },
  },
  {
    number: 6,
    slug: "letters-are-numbers",
    title: "Letters are numbers",
    dek: "Letters, words, even pictures — all just numbers you print.",
    published: true,
    durationSec: 119,
    music: { season: "Tchaikovsky", piece: "Trepak · Russian Dance (Nutcracker, Op. 71)" },
    concepts: [
      "emit prints one character from its number — 42 is *, and 65 66 67 are A B C. A letter is just a number you print.",
      'A word can hold text too: : dog ." the dog" ; — then string printing-words into a sentence. Words from words, applied to letters.',
      's" hands you a string as a pair — an address and a count — and type prints it. That same pair is what pay-rent fed send back in episode four.',
    ],
    // Every word is defined inline, so the whole lesson runs on a fresh install.
    codeAlong: [
      '." hello, i speak forth"',
      "42 emit",
      "65 emit 66 emit 67 emit",
      ": star  42 emit ;",
      "star",
      "32 emit",
      ': dog  ." the dog" ;',
      ': runs  ." runs" ;',
      ': home  ." home." ;',
      ": story  dog space runs space home cr ;",
      "story",
      ": s1  cr star ;",
      ": s2  s1 star ;",
      ": s3  s2 star ;",
      ": s4  s3 star ;",
      ": s5  s4 star ;",
      ": s6  s5 star ;",
      ": s7  s6 star ;",
      ": tri  s1 s2 s3 s4 s5 s6 s7 cr ;",
      "tri",
      's" forth" type',
    ],
    transcript: [
      "we've moved numbers around. but what about letters?",
      "two ways to print. first — just text.",
      "dot-quote prints what you typed. the quotes hold the words.",
      "the other way — one letter at a time.",
      "forty-two — a star came out.",
      "wait. one number, one character?",
      "a, b, c — next number, next letter. letters are just numbers.",
      "name it once — now star's a word.",
      "thirty-two? just a blank — a space is a number too.",
      "a word can hold text, too — not just a number.",
      "now string them — a space between each. that's a word too, remember.",
      "a sentence — built from words.",
      "...the dog. that's me, by the way.",
      "and the same words draw pictures.",
      "letters, words, pictures — all just numbers you print.",
      "and a whole word at once?",
      "s-quote hands you a string — an address, and a length.",
      "type prints all of it — given where, and how many.",
      "remember this pair — an address, and a count?",
      "that's exactly what pay-rent fed send, back in episode four.",
      "a string, and where it goes.",
      "more in episode ten.",
      "henceforth.",
    ],
    video: { mp4: "/learn/letters-are-numbers/episode.mp4" },
  },
  {
    number: 7,
    slug: "decisions",
    title: "Decisions",
    dek: "Give forth a yes-or-no and it picks a path — if, else, then, and decisions inside decisions.",
    published: true,
    durationSec: 97,
    music: { season: "Tchaikovsky", piece: "March (Nutcracker, Op. 71)" },
    concepts: [
      'if … else … then picks a path from a yes-or-no on the stack: : positive?  dup 0 > if ." positive!" else ." not positive." then drop ;',
      "Any non-zero is true; zero is the only no. The condition is just a number — even? tests dup 2 mod 0 = and decides from it.",
      'Decisions nest inside decisions — sign-of asks "over zero?", then in the else asks again. Bitcoin Script branches the same way: if a signature checks, spend; else, don\'t.',
    ],
    // Every word is defined inline, so the whole lesson runs on a fresh install.
    codeAlong: [
      ': positive?  dup 0 > if ." positive!" cr else ." not positive." cr then drop ;',
      "5 positive?",
      "-3 positive?",
      ': even?  dup 2 mod 0 = if ." even." cr else ." odd." cr then drop ;',
      "6 even?",
      "7 even?",
      ': sign-of  cr ." the sign of: " dup . cr dup 0 > if ." positive" cr else dup 0 < if ." negative" cr else ." zero" cr then then drop ;',
      "0 sign-of",
      "5 sign-of",
      "-3 sign-of",
    ],
    transcript: [
      "every word so far just runs. can one... choose?",
      "give forth a yes-or-no, and it picks a path.",
      "if the number is over zero, say so. otherwise, the other branch.",
      "five is positive — the if branch ran.",
      "minus three took the else. same word, two paths.",
      "and what counts as yes?",
      "any non-zero is true. zero is the only no.",
      "the test can be computed — remainder by two, is it zero?",
      "six yes, seven no. the condition is just a number on the stack.",
      "can a decision hold another?",
      "over zero? positive. else, ask again — under zero, or nothing at all.",
      "zero, positive, negative — decisions inside decisions.",
      "why teach the dog to choose?",
      "bitcoin script branches the same way — if a signature checks, spend; else, don't.",
      "every spending rule is a decision.",
      "more in episode ten.",
      "henceforth.",
    ],
    video: { mp4: "/learn/decisions/episode.mp4" },
  },
  {
    number: 8,
    slug: "loops",
    title: "Loops",
    dek: "Teach the dog to repeat — count up, count down, compound, and ask a question every step.",
    published: true,
    durationSec: 162,
    music: { season: "Tchaikovsky", piece: "Waltz of the Flowers (Nutcracker, Op. 71)" },
    concepts: [
      "do … loop counts between two numbers, and they go on the stack first: 11 1 do runs i from 1 up to 10 — it stops just before the limit.",
      "begin … until loops until a test comes true — the counter lives on the stack the whole way down, with dup to peek and 1 - to step it.",
      "An if inside a loop asks a question every step: 101 0 do i prime? if i . then loop prints every prime under a hundred — a loop, a decision, and the stack.",
    ],
    // Every word is defined inline (the prime? helpers too), so the whole lesson
    // runs on a fresh install. The video pre-loads prime?; here it's spelled out.
    codeAlong: [
      ': count-up  cr ." counting:" cr  11 1 do  i .  cr  loop  ." done." cr ;',
      "count-up",
      ': countdown  cr ." liftoff in:" cr  10  begin  dup .  cr  1 - dup 0 =  until  drop ." liftoff!" cr ;',
      "countdown",
      ': grow  cr ." 100 sats at 12%/yr:" cr  100  11 1 do  112 100 */  ." yr" space i .  ." :" space dup .  cr  loop  drop ." compounded." cr ;',
      "grow",
      "variable candidate",
      "variable composite",
      ": divides?  candidate @ swap mod 0= ;",
      ": worth-testing?  dup dup * candidate @ > 0= ;",
      ": prime?  candidate !  candidate @ 2 < if false exit then  candidate @ 2 = if true exit then  candidate @ 2 mod 0= if false exit then  false composite !  3  begin worth-testing? while  dup divides? if true composite ! then  2 +  repeat drop  composite @ 0= ;",
      ': primes  cr ." primes 0..100:" cr  101 0 do i prime? if i . then loop cr ;',
      "primes",
    ],
    transcript: [
      "every word so far runs once. what if i want it again — and again?",
      "a loop. i write the steps once, and say how many.",
      "first, two numbers land on the stack — eleven, then one.",
      "do takes them both: start at one, stop just before eleven.",
      "one, two, three … ten. ten loops.",
      "and each turn, i drops on the stack — the dot prints it, then clears it off.",
      "and when i don't know how many times?",
      "ten goes on the stack — and stays there, counting.",
      "dup copies it to print; 1 - takes one off the top.",
      "until checks the top: is it zero yet?",
      "watch the stack count itself down — ten to one.",
      "loops do real work. watch money grow.",
      "twelve percent a year is times 112, over 100 — the */ word.",
      "100 sats sit on the stack — the running total.",
      "the same do loop — one to ten. ten years.",
      "each year, */ grows the total on the stack. 100 becomes 304 — it triples.",
      "and a decision, inside a loop?",
      "prime? is already written — it asks if a number has any divisor.",
      "this loop runs zero to a hundred.",
      "each turn, i goes on the stack; prime? takes it, leaves a yes or no.",
      "if yes — print it.",
      "every prime under a hundred — a loop, asking a question of the stack.",
      "why teach the dog to repeat?",
      "bitcoin script loops too — counting, checking, until a rule is met.",
      "more in episode ten.",
      "henceforth.",
    ],
    video: { mp4: "/learn/loops/episode.mp4" },
  },
  {
    number: 9,
    slug: "three-stacks",
    title: "The three stacks",
    dek: "One stack is yours, one is the machine's — and the third belongs to bitcoin.",
    published: true,
    durationSec: 154,
    music: { season: "Vivaldi", piece: "Double Concerto in A minor · Allegro (RV 522 i)" },
    concepts: [
      ">r takes the top of your stack and sets it down on the return stack — the machine's own pile. r> is the exact reverse: it brings the number home, and you never named it once.",
      ".s shows your stack, .rs the return stack, .ds the data stack — three stacks, three owners: yours, the machine's, and bitcoin's.",
      "Reaching into an empty pile is an error, not a mystery: r> on an empty return stack reports return stack underflow — each of the three stacks has its own floor.",
    ],
    codeAlong: [
      "7 8 .s",
      "42 >r",
      ".s",
      ".rs",
      "r>",
      ".s",
      ".ds",
      "r>",
    ],
    transcript: [
      "one pile of numbers — that's all there is?",
      "no. henceforth runs three stacks. three owners.",
      "the first is yours — you've pushed numbers to it since episode two.",
      ".s shows your stack — 7, then 8.",
      "8 landed last, so 8 sits on top.",
      "but where does the machine itself hold a number for later?",
      "i push 42 onto your stack first.",
      "then >r takes that top number — the 42 — straight off your stack...",
      "...and sets it down on the return stack — the machine's own pile.",
      "watch your stack — back to two. 7 and 8. the 42 is gone.",
      ".rs shows the return stack — the machine's own.",
      "there's the 42, held for later. no variable needed.",
      "and to pull it back onto yours?",
      "r> is the exact reverse of >r.",
      "it takes the top of the return stack — the 42 — and sets it back on your stack.",
      "your stack now — 7, 8, 42. the 42 came home, sitting on top.",
      "moved to the machine's pile and back — and you never named it once.",
      "and the third stack?",
      ".ds prints the data stack. empty for now.",
      "not yours. not the machine's.",
      "this one is bitcoin's — the consensus stack a script runs on.",
      "next episode, we put the first values onto it.",
      "and reaching into an empty stack?",
      "the return stack's empty — the 42's already home.",
      "r> reaches for the top — and there's nothing to take. return stack underflow.",
      "one floor of three — each stack has its own.",
      "three stacks. one yours, one the machine's, one bitcoin's.",
      "you've worked two of them today.",
      "the third is the whole point of next time.",
      "henceforth.",
    ],
    video: { mp4: "/learn/three-stacks/episode.mp4" },
  },
];

const byNumber = [...episodes].sort((a, b) => a.number - b.number);

export function publishedEpisodes(): Episode[] {
  return byNumber.filter((e) => e.published);
}

export function getEpisode(slug: string): Episode | undefined {
  return episodes.find((e) => e.slug === slug);
}

// Neighbours by episode number across ALL episodes, so the page can tease an
// unpublished "next … soon". The page decides whether to link based on .published.
export function adjacentEpisodes(slug: string): { prev?: Episode; next?: Episode } {
  const i = byNumber.findIndex((e) => e.slug === slug);
  if (i === -1) return {};
  return { prev: byNumber[i - 1], next: byNumber[i + 1] };
}

export function formatDuration(sec?: number): string | undefined {
  if (!sec) return undefined;
  const m = Math.floor(sec / 60);
  const s = Math.round(sec % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}
