export type Episode = {
  number: number;
  slug: string;
  title: string;
  dek: string;
  published: boolean;
  durationSec?: number; // set from the rendered mp4
  music?: { season: string; piece: string };
  concepts?: string[];
  codeAlong?: string[];
  transcript?: string[];
  video?: { mp4: string };
};

export const episodes: Episode[] = [
  {
    number: 1,
    slug: "what-is-henceforth",
    title: "What is Henceforth?",
    dek: "A calculator you can teach — that also writes Bitcoin.",
    published: true,
    durationSec: 98,
    music: { season: "Spring", piece: "Vivaldi · Allegro (RV 269 i)" },
    concepts: [
      "FORTH is a calculator you talk to in postfix: 2 3 + .",
      "You can teach it new words — : double 2 * ; — then reuse them.",
      "The same machine writes Bitcoin Script, and a payment reads like a sentence.",
    ],
    // Curated to commands that run on a fresh install — tutorial-only lesson
    // words (program-intro, henceforth?) are excluded; a new app hasn't defined them.
    codeAlong: [
      "2 3 +",
      ".",
      ": double  2 * ;",
      "21 double .",
      "SCRIPT-BEGIN",
      "OP_DUP OP_HASH160 OP_EQUALVERIFY OP_CHECKSIG",
      "SCRIPT-END",
      ': pay-rent  1000 s" 1Q88RPbgtGfaDvQYd9Yx3UC86vAhcDSjob" send ;',
    ],
    transcript: [
      "so — what IS this thing?",
      "watch. it answers by doing.",
      "give it two numbers… and +.",
      "it added them. it's a calculator.",
      "but here's the good part —",
      "i just taught it a word.",
      "double means times two.",
      "see that? it knows double now.",
      "words you make. that's the idea.",
      "now… the other half.",
      "same prompt. watch closely.",
      "these are bitcoin words.",
      "that's the shape of a coin-lock.",
      "same machine. just more words.",
      "one last word — read it slow.",
      "pay rent: send 1000 there.",
      "it reads like a sentence.",
      "and it's also a payment.",
      "that's henceforth.",
      "one prompt. you teach it. let's go.",
    ],
    video: { mp4: "/learn/what-is-henceforth/episode.mp4" },
  },
  {
    number: 2,
    slug: "the-stack",
    title: "The Stack",
    dek: "Numbers live in a pile — newest on top, newest off first.",
    published: true,
    durationSec: 74,
    music: { season: "Summer", piece: "Vivaldi · Presto (RV 315 iii)" },
    concepts: [
      "Numbers pile up on a stack — the newest is always on top.",
      "Operators take from the top: + eats the top two, . prints the top.",
      "Take one too many and you hit underflow — the stack only returns what you put in.",
    ],
    codeAlong: ["3 4 5", "+", "+", ".", "10 20 30", ". . . ."],
    transcript: [
      "but where do the numbers go? onto a pile.",
      "a 3. a 4 on top. a 5 — newest always on top.",
      "that's the stack — a pile of numbers, just waiting.",
      "now watch + eat from it.",
      "+ takes the top two — the 5 and the 4 — and leaves a 9.",
      "again — 3 and 9. now just 12.",
      ". prints the top. there's the 12.",
      "you only ever touch the top.",
      "last on, first off — like a can of tennis balls.",
      "let's empty one right out. three on the pile, 30 on top.",
      "30… 20… 10. empty.",
      "now — one more than we put in. nothing's there.",
      "underflow. you hit the floor — and see, it didn't say ok.",
      "the stack gives back exactly what you put in.",
    ],
    video: { mp4: "/learn/the-stack/episode.mp4" },
  },
  {
    number: 3,
    slug: "backwards-maths",
    title: "Why the maths looks backwards",
    dek: "Postfix, and why the stack is the parentheses.",
    published: true,
    durationSec: 123,
    music: { season: "Autumn", piece: "Vivaldi · Allegro (RV 293 i)" },
    concepts: [
      "You write the numbers first, then the operation — 2 3 + . That's reverse Polish (postfix).",
      "The stack remembers as you go, so 2 3 + 4 * nests without any brackets.",
      "Because the last two numbers already sit on the stack, Fibonacci is one little word: : next-fib  tuck + ;.",
    ],
    codeAlong: [
      "2 3 +",
      ".",
      "2 3 + 4 *",
      ".",
      ": next-fib  tuck + ;",
      "1 1",
      "next-fib .s",
      "next-fib .s",
      "next-fib .s",
      "2drop",
      "2 + 3",
    ],
    transcript: [
      "you already know how to add.",
      "watch how this little machine wants it.",
      "you put the numbers down first —",
      "two, then three.",
      "then you say: add.",
      "five. the plus reached back and grabbed the two.",
      "numbers first, then the operation —",
      "that's reverse polish.",
      "and it stacks up — no brackets.",
      "two plus three is five —",
      "then five times four.",
      "twenty. the stack just remembers.",
      "now — one that's a headache in most languages.",
      "the fibonacci numbers — each one the last two, added.",
      "python needs a loop and two boxes to hold them.",
      "but our two numbers already sit on the stack.",
      "so it's one little word.",
      "take the pair, make the next one.",
      "start it with two ones.",
      "now nudge it forward — again and again.",
      "and it just keeps climbing —",
      "a hundred and forty-four — the twelfth.",
      "fibonacci. in one little word.",
      "clear the pair —",
      "and the school way? watch it break.",
      "no — the plus went looking for two numbers,",
      "and found nothing behind it.",
      "numbers first. that's the whole trick.",
      "henceforth.",
    ],
    video: { mp4: "/learn/backwards-maths/episode.mp4" },
  },
  {
    number: 4,
    slug: "words-from-words",
    title: "Words from words",
    dek: "Words made from words — all the way down to a payment.",
    published: true,
    durationSec: 113,
    music: { season: "Winter", piece: "Vivaldi · Allegro (RV 297 i)" },
    concepts: [
      "A colon definition teaches a new word: : double  2 * ; — then it's yours, used like any built-in.",
      "Bigger words are built from the small ones — quadruple is double double, square is dup *, cube is dup square *. Factoring, all the way down.",
      "Mistype a word and Henceforth points you home with a did you mean? hint — and a payment, : pay-rent … send ;, is defined the exact same way.",
    ],
    // Every word here is defined inline, so the whole lesson runs on a fresh
    // install. squre is the deliberate typo that triggers the did-you-mean hint.
    codeAlong: [
      ": double  2 * ;",
      "21 double .",
      "see double",
      ": quadruple  double double ;",
      "5 quadruple .",
      ": square  dup * ;",
      "7 square .",
      ": cube  dup square * ;",
      "3 cube .",
      "squre",
      ': pay-rent  1000 s" 1Q88RPbgtGfaDvQYd9Yx3UC86vAhcDSjob" send ;',
    ],
    transcript: [
      "last time — small words made big maths.",
      "but where do the small words come from?",
      "you make them. watch.",
      "double. you taught it this — episode one.",
      "still here. yours, and built-in, all at once.",
      "and you can look inside. there's its recipe.",
      "now — a bigger word, from the one you made.",
      "quadruple. just double — twice.",
      "twenty. a word, standing on a word.",
      "what if a word needs its number twice?",
      "you copy the top. that's dup.",
      "dup copies it — then times itself.",
      "forty-nine. seven, squared.",
      "cube stands on square — square stands on dup.",
      "small words. all the way down.",
      "and a word you never taught it?",
      "no — it only knows the words you made.",
      "but see — it points you home.",
      "one more. remember this — from episode one?",
      "that bitcoin word? it was a word i defined.",
      "same colon. same semicolon. same : ... ;",
      "a payment is just another word you teach.",
      "henceforth.",
    ],
    video: { mp4: "/learn/words-from-words/episode.mp4" },
  },
  {
    number: 5,
    slug: "moving-numbers",
    title: "Moving numbers",
    dek: "The shuffle words change where numbers sit — never what they are.",
    published: true,
    durationSec: 95,
    music: { season: "Bach", piece: "Brandenburg No. 3 · Allegro (BWV 1048 i)" },
    concepts: [
      "The stack only ever hands you its top — so to use a number twice, in a new order, or from underneath, you reach for a mover: dup, swap, over, rot, drop.",
      "Movers change where numbers sit, never what they are. swap flips the top two, so 10 4 swap - leaves 4 - 10 = -6 — same numbers, new order.",
      "A mover still needs operands — swap on a one-item stack hits the floor (underflow). Bitcoin Script has the same move, OP_DUP, which you'll wield in episode ten.",
    ],
    // Every command is typed live at the prompt, so the whole lesson runs on a
    // fresh install. The final bare swap is the deliberate underflow.
    codeAlong: [
      "7 dup .s",
      "2drop",
      "10 4 .s",
      "swap .s",
      "- .",
      "1 2 over .s",
      "2drop drop",
      "1 2 3 rot .s",
      "2drop drop",
      "7 8 drop .s",
      "swap",
    ],
    transcript: [
      "last time — you copied the top.",
      "that was dup. it made square.",
      "dup's got a family — words that just move numbers.",
      "because the stack only ever hands you the top.",
      "dup — copy the top. you've met this one.",
      "what if they're backwards?",
      "i want 4 minus 10 — but 4's on top.",
      "swap — flip the top two.",
      "minus six. same numbers, new order.",
      "and the one underneath?",
      "over — copy the second one up top.",
      "buried deeper?",
      "rot — bring the bottom one up.",
      "and when you don't need it?",
      "drop — throw the top away. pretty simple, huh?",
      "but they still need numbers to move.",
      "give swap one — it hits the floor.",
      "movers need a stocked stack.",
      "watch — none of them did math.",
      "they only move numbers. never change what they are.",
      "bitcoin has this same move — op_dup.",
      "you'll wield it in episode ten.",
      "henceforth.",
    ],
    video: { mp4: "/learn/moving-numbers/episode.mp4" },
  },
  {
    number: 6,
    slug: "letters-are-numbers",
    title: "Letters are numbers",
    dek: "Letters, words, even pictures — all just numbers you print.",
    published: true,
    durationSec: 119,
    music: { season: "Tchaikovsky", piece: "Trepak · Russian Dance (Nutcracker, Op. 71)" },
    concepts: [
      "emit prints one character from its number — 42 is *, and 65 66 67 are A B C. A letter is just a number you print.",
      'A word can hold text too: : dog ." the dog" ; — then string printing-words into a sentence. Words from words, applied to letters.',
      's" hands you a string as a pair — an address and a count — and type prints it. That same pair is what pay-rent fed send back in episode four.',
    ],
    // Every word is defined inline, so the whole lesson runs on a fresh install.
    codeAlong: [
      '." hello, i speak forth"',
      "42 emit",
      "65 emit 66 emit 67 emit",
      ": star  42 emit ;",
      "star",
      "32 emit",
      ': dog  ." the dog" ;',
      ': runs  ." runs" ;',
      ': home  ." home." ;',
      ": story  dog space runs space home cr ;",
      "story",
      ": s1  cr star ;",
      ": s2  s1 star ;",
      ": s3  s2 star ;",
      ": s4  s3 star ;",
      ": s5  s4 star ;",
      ": s6  s5 star ;",
      ": s7  s6 star ;",
      ": tri  s1 s2 s3 s4 s5 s6 s7 cr ;",
      "tri",
      's" forth" type',
    ],
    transcript: [
      "we've moved numbers around. but what about letters?",
      "two ways to print. first — just text.",
      "dot-quote prints what you typed. the quotes hold the words.",
      "the other way — one letter at a time.",
      "forty-two — a star came out.",
      "wait. one number, one character?",
      "a, b, c — next number, next letter. letters are just numbers.",
      "name it once — now star's a word.",
      "thirty-two? just a blank — a space is a number too.",
      "a word can hold text, too — not just a number.",
      "now string them — a space between each. that's a word too, remember.",
      "a sentence — built from words.",
      "...the dog. that's me, by the way.",
      "and the same words draw pictures.",
      "letters, words, pictures — all just numbers you print.",
      "and a whole word at once?",
      "s-quote hands you a string — an address, and a length.",
      "type prints all of it — given where, and how many.",
      "remember this pair — an address, and a count?",
      "that's exactly what pay-rent fed send, back in episode four.",
      "a string, and where it goes.",
      "more in episode ten.",
      "henceforth.",
    ],
    video: { mp4: "/learn/letters-are-numbers/episode.mp4" },
  },
  {
    number: 7,
    slug: "decisions",
    title: "Decisions",
    dek: "Give forth a yes-or-no and it picks a path — if, else, then, and decisions inside decisions.",
    published: true,
    durationSec: 97,
    music: { season: "Tchaikovsky", piece: "March (Nutcracker, Op. 71)" },
    concepts: [
      'if … else … then picks a path from a yes-or-no on the stack: : positive?  dup 0 > if ." positive!" else ." not positive." then drop ;',
      "Any non-zero is true; zero is the only no. The condition is just a number — even? tests dup 2 mod 0 = and decides from it.",
      'Decisions nest inside decisions — sign-of asks "over zero?", then in the else asks again. Bitcoin Script branches the same way: if a signature checks, spend; else, don\'t.',
    ],
    // Every word is defined inline, so the whole lesson runs on a fresh install.
    codeAlong: [
      ': positive?  dup 0 > if ." positive!" cr else ." not positive." cr then drop ;',
      "5 positive?",
      "-3 positive?",
      ': even?  dup 2 mod 0 = if ." even." cr else ." odd." cr then drop ;',
      "6 even?",
      "7 even?",
      ': sign-of  cr ." the sign of: " dup . cr dup 0 > if ." positive" cr else dup 0 < if ." negative" cr else ." zero" cr then then drop ;',
      "0 sign-of",
      "5 sign-of",
      "-3 sign-of",
    ],
    transcript: [
      "every word so far just runs. can one... choose?",
      "give forth a yes-or-no, and it picks a path.",
      "if the number is over zero, say so. otherwise, the other branch.",
      "five is positive — the if branch ran.",
      "minus three took the else. same word, two paths.",
      "and what counts as yes?",
      "any non-zero is true. zero is the only no.",
      "the test can be computed — remainder by two, is it zero?",
      "six yes, seven no. the condition is just a number on the stack.",
      "can a decision hold another?",
      "over zero? positive. else, ask again — under zero, or nothing at all.",
      "zero, positive, negative — decisions inside decisions.",
      "why teach the dog to choose?",
      "bitcoin script branches the same way — if a signature checks, spend; else, don't.",
      "every spending rule is a decision.",
      "more in episode ten.",
      "henceforth.",
    ],
    video: { mp4: "/learn/decisions/episode.mp4" },
  },
  {
    number: 8,
    slug: "loops",
    title: "Loops",
    dek: "Teach the dog to repeat — count up, count down, compound, and ask a question every step.",
    published: true,
    durationSec: 162,
    music: { season: "Tchaikovsky", piece: "Waltz of the Flowers (Nutcracker, Op. 71)" },
    concepts: [
      "do … loop counts between two numbers, and they go on the stack first: 11 1 do runs i from 1 up to 10 — it stops just before the limit.",
      "begin … until loops until a test comes true — the counter lives on the stack the whole way down, with dup to peek and 1 - to step it.",
      "An if inside a loop asks a question every step: 101 0 do i prime? if i . then loop prints every prime under a hundred — a loop, a decision, and the stack.",
    ],
    // Every word is defined inline (the prime? helpers too), so the whole lesson
    // runs on a fresh install. The video pre-loads prime?; here it's spelled out.
    codeAlong: [
      ': count-up  cr ." counting:" cr  11 1 do  i .  cr  loop  ." done." cr ;',
      "count-up",
      ': countdown  cr ." liftoff in:" cr  10  begin  dup .  cr  1 - dup 0 =  until  drop ." liftoff!" cr ;',
      "countdown",
      ': grow  cr ." 100 sats at 12%/yr:" cr  100  11 1 do  112 100 */  ." yr" space i .  ." :" space dup .  cr  loop  drop ." compounded." cr ;',
      "grow",
      "variable candidate",
      "variable composite",
      ": divides?  candidate @ swap mod 0= ;",
      ": worth-testing?  dup dup * candidate @ > 0= ;",
      ": prime?  candidate !  candidate @ 2 < if false exit then  candidate @ 2 = if true exit then  candidate @ 2 mod 0= if false exit then  false composite !  3  begin worth-testing? while  dup divides? if true composite ! then  2 +  repeat drop  composite @ 0= ;",
      ': primes  cr ." primes 0..100:" cr  101 0 do i prime? if i . then loop cr ;',
      "primes",
    ],
    transcript: [
      "every word so far runs once. what if i want it again — and again?",
      "a loop. i write the steps once, and say how many.",
      "first, two numbers land on the stack — eleven, then one.",
      "do takes them both: start at one, stop just before eleven.",
      "one, two, three … ten. ten loops.",
      "and each turn, i drops on the stack — the dot prints it, then clears it off.",
      "and when i don't know how many times?",
      "ten goes on the stack — and stays there, counting.",
      "dup copies it to print; 1 - takes one off the top.",
      "until checks the top: is it zero yet?",
      "watch the stack count itself down — ten to one.",
      "loops do real work. watch money grow.",
      "twelve percent a year is times 112, over 100 — the */ word.",
      "100 sats sit on the stack — the running total.",
      "the same do loop — one to ten. ten years.",
      "each year, */ grows the total on the stack. 100 becomes 304 — it triples.",
      "and a decision, inside a loop?",
      "prime? is already written — it asks if a number has any divisor.",
      "this loop runs zero to a hundred.",
      "each turn, i goes on the stack; prime? takes it, leaves a yes or no.",
      "if yes — print it.",
      "every prime under a hundred — a loop, asking a question of the stack.",
      "why teach the dog to repeat?",
      "bitcoin script loops too — counting, checking, until a rule is met.",
      "more in episode ten.",
      "henceforth.",
    ],
    video: { mp4: "/learn/loops/episode.mp4" },
  },
  {
    number: 9,
    slug: "three-stacks",
    title: "The three stacks",
    dek: "One stack is yours, one is the machine's — and the third belongs to bitcoin.",
    published: true,
    durationSec: 154,
    music: { season: "Vivaldi", piece: "Double Concerto in A minor · Allegro (RV 522 i)" },
    concepts: [
      ">r takes the top of your stack and sets it down on the return stack — the machine's own pile. r> is the exact reverse: it brings the number home, and you never named it once.",
      ".s shows your stack, .rs the return stack, .ds the data stack — three stacks, three owners: yours, the machine's, and bitcoin's.",
      "Reaching into an empty pile is an error, not a mystery: r> on an empty return stack reports return stack underflow — each of the three stacks has its own floor.",
    ],
    codeAlong: [
      "7 8 .s",
      "42 >r",
      ".s",
      ".rs",
      "r>",
      ".s",
      ".ds",
      "r>",
    ],
    transcript: [
      "one pile of numbers — that's all there is?",
      "no. henceforth runs three stacks. three owners.",
      "the first is yours — you've pushed numbers to it since episode two.",
      ".s shows your stack — 7, then 8.",
      "8 landed last, so 8 sits on top.",
      "but where does the machine itself hold a number for later?",
      "i push 42 onto your stack first.",
      "then >r takes that top number — the 42 — straight off your stack...",
      "...and sets it down on the return stack — the machine's own pile.",
      "watch your stack — back to two. 7 and 8. the 42 is gone.",
      ".rs shows the return stack — the machine's own.",
      "there's the 42, held for later. no variable needed.",
      "and to pull it back onto yours?",
      "r> is the exact reverse of >r.",
      "it takes the top of the return stack — the 42 — and sets it back on your stack.",
      "your stack now — 7, 8, 42. the 42 came home, sitting on top.",
      "moved to the machine's pile and back — and you never named it once.",
      "and the third stack?",
      ".ds prints the data stack. empty for now.",
      "not yours. not the machine's.",
      "this one is bitcoin's — the consensus stack a script runs on.",
      "next episode, we put the first values onto it.",
      "and reaching into an empty stack?",
      "the return stack's empty — the 42's already home.",
      "r> reaches for the top — and there's nothing to take. return stack underflow.",
      "one floor of three — each stack has its own.",
      "three stacks. one yours, one the machine's, one bitcoin's.",
      "you've worked two of them today.",
      "the third is the whole point of next time.",
      "henceforth.",
    ],
    video: { mp4: "/learn/three-stacks/episode.mp4" },
  },
  {
    number: 10,
    slug: "bitcoin-script",
    title: "Bitcoin script",
    dek: "Everything you've typed since episode two was bitcoin all along — watch a real lock assemble, byte by byte.",
    published: true,
    durationSec: 192,
    music: { season: "Bach", piece: "Brandenburg No. 3 · Allegro (BWV 1048 i)" },
    concepts: [
      "Every op code is a standard FORTH word dressed for bitcoin — op_3 op_4 op_add is episode two's sum, and op_dup is just dup, running on the same data stack you've used all series.",
      "script-begin flips the terminal into recording: every word now writes bytes instead of executing. op_dup op_hash160, twenty bytes of hash, op_equalverify op_checksig — the pay-to-public-key-hash lock assembles live, twenty-five bytes guarding satoshi's block-zero address.",
      "A lock is a program you run to open. checksig-fixture arms a signed transaction, then the lock replays word by word — op_dup, op_hash160, the hash, op_equalverify, op_checksig — until the stack reads VALID.",
      "Your own words write bytes too: : lock5 5 0 do op_dup loop ; records five dups from a LOOP. Definitions, loops, all of FORTH — aimed at the chain.",
    ],
    codeAlong: [
      "op_3 op_4 op_add .ds",
      "op_3 op_dup .ds",
      "script-begin",
      "op_dup op_hash160",
      "0x62e907b15cbf27d5425399ebf6f0fb50ebb88f18",
      "op_equalverify op_checksig",
      "script-end",
      "checksig-fixture",
      ": lock5 5 0 do op_dup loop ;",
    ],
    transcript: [
      "and now... bitcoin?",
      "bitcoin is FORTH too!",
      "stack-based. postfix. words.",
      "every transaction carries a small script.",
      "you already know it.",
      "episode two. three plus four — your stack.",
      "the same sum — spoken in bitcoin.",
      "seven. same words. same order. bitcoin's stack.",
      "even drop came along.",
      "look: op_dup is just dup. same word. same data stack.",
      "every op code is a standard FORTH word — dressed for bitcoin.",
      "pay-to-public-key-hash:",
      "OP_DUP OP_HASH160 <hash> OP_EQUALVERIFY OP_CHECKSIG",
      "that's the lock on nearly every address.",
      "want to write one? satoshi's own lock?",
      "recording. every word now writes bytes.",
      "duplicate the key. hash it.",
      "twenty bytes. satoshi's address — block zero.",
      "match the hash. check the signature.",
      "twenty-five bytes. a real bitcoin lock.",
      "but can you open it?",
      "nobody has satoshi's key. that missing key is the entire idea.",
      "so bring your own — and a real signature.",
      "a signed transaction. sig and key on bitcoin's stack.",
      "now run the lock. word by word.",
      "copy the key. hash it. the hash the lock demands.",
      "match — or the script dies. still alive.",
      "...the signature check. the real one.",
      "VALID. that's not a picture of bitcoin.",
      "that's bitcoin — run by the words you already know.",
      "one more thing. the henceforth secret.",
      "a word of your own. five dups — from a loop.",
      "your word runs — and writes bytes.",
      "six bytes. five dups from a LOOP.",
      "definitions. loops. all of FORTH — aimed at the chain.",
      "ten episodes. one stack language.",
      "every transaction. just FORTH.",
      "henceforth.",
    ],
    video: { mp4: "/learn/bitcoin-script/episode.mp4" },
  },
  {
    number: 11,
    slug: "the-address",
    title: "The address",
    dek: "An address is not a place — it is twenty bytes wearing clothes. Meet the address book: names you can pay.",
    published: true,
    durationSec: 142,
    music: { season: "Handel", piece: "Water Music, Suite No. 3 in G · Menuet (United States Marine Band, 2017, public domain)" },
    concepts: [
      "An address is a hash160 dressed for humans — a version byte in front, a four-byte checksum seal on the end, spelled in base58 with nothing you can misread.",
      "The world's first public key — block zero, satoshi's — folds through op_hash160 to 62e9…8f18: the exact twenty bytes episode ten typed into its lock.",
      "Coins are locked to the bytes, not stored at the address. The chain holds the money; the address is the name on the lock.",
      "Contacts are vocabulary: : satoshi  s\" 1A1zP1…\" ; makes a name you can pay — the season's first everyday tool, and pay-rent finally reads like a sentence.",
    ],
    // Curated to commands that run on a fresh install — lesson narration words
    // (address-intro, first-key, clothes) are excluded; a new app hasn't defined them.
    codeAlong: [
      "7 dup + .",
      "op_7 op_dup op_add .ds",
      "op_drop",
      's" 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f" hex>data',
      "op_hash160",
      ".ds",
      ': satoshi  s" 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa" ;',
      "satoshi type",
      ': landlord  s" 1Q88RPbgtGfaDvQYd9Yx3UC86vAhcDSjob" ;',
      ": pay-rent  1000 landlord send ;",
    ],
    transcript: [
      "so where does money actually live?",
      "episode eleven. the address.",
      "from block zero to your pocket.",
      "first — the twin. episode two taught dup.",
      "seven doubled. fourteen.",
      "the same twin in bitcoin. fourteen on both stacks.",
      "so an address... is it a place?",
      "no. it is a hash wearing clothes. watch.",
      "the world's first public key. block zero. satoshi's:",
      "sixty five bytes of public key.",
      "hashed twice. sixty five bytes fold to twenty.",
      "episode ten — you typed these exact bytes into a lock.",
      "coins are locked to the bytes. that is where money lives.",
      "an address is those twenty bytes, dressed:",
      "a version byte in front.",
      "a four byte seal on the end - c29b7d93.",
      "spelled in base58. no 0, no O - nothing to misread.",
      "and satoshi's address? the famous one?",
      "there. the same twenty bytes — 62e9 — wearing clothes.",
      "do i have to remember that string?",
      "you never will again. you just named it. a contact, one word.",
      "episode one wrote pay-rent around a pasted string.",
      "now it reads like a sentence. defined — not run. that day is episode twenty.",
      "an address book. the season's first tool. names you can pay.",
      "and yours? the receive word raises it — once a wallet lives in your pocket.",
      "money never sits at an address. the chain holds it, locked to the bytes behind the name.",
      "henceforth.",
    ],
    video: { mp4: "/learn/the-address/episode.mp4" },
  },
  {
    number: 12,
    slug: "the-transaction",
    title: "The transaction",
    dek: "How money moves — by never moving. A coin sits in a list behind a lock; paying opens an old lock and makes a new one.",
    published: true,
    durationSec: 97,
    music: { season: "Handel", piece: "Water Music · Sarabande (United States Marine Band, public domain)" },
    concepts: [
      "A coin does not travel. It sits in a list, behind a lock — to pay, an old lock is opened and a new one is made.",
      "A transaction is entries waiting to exist: outputs addressed to names from the address book, built in practice mode before anything is real.",
      "The coins you pay with are picked by your wallet at send time — old coins in, new coins out, like coins into a till with fresh change coming back.",
      "The swap twin: two numbers trading places on the stack is the same move bitcoin makes with coins.",
    ],
    // Curated to commands that run on a fresh install — lesson narration words
    // (tx-intro, not-moved, where-inputs) are excluded; a new app hasn't defined them.
    codeAlong: [
      "1 2 swap . .",
      "tx-preview-toggle",
      "tx-new",
      ': mum  s" 1Q88RPbgtGfaDvQYd9Yx3UC86vAhcDSjob" ;',
      "800 mum tx-add-output",
      "tx-show",
      "tx-clear",
      "tx-preview-toggle",
    ],
    transcript: [
      "so how does money actually move?",
      "episode twelve. the transaction.",
      "how money moves - by never moving.",
      "when i pay you... my coin travels to you?",
      "a coin does not travel.",
      "it sits in a list, behind a lock.",
      "to pay: an old lock is opened -",
      "and a new one is made.",
      "like coins into a till - and your change comes out fresh.",
      "watch two numbers trade places.",
      "swap. bitcoin does the same with coins - old ones in, new ones out.",
      "let's build one. practice mode - nothing is real today.",
      "mum, from last week's address book.",
      "eight hundred - to a name, not a number.",
      "one entry, waiting to exist. that is a transaction.",
      "the coins you pay WITH?",
      "your wallet picks them at send time.",
      "old coins in. new coins out.",
      "money never moves. it is used up - and made again, behind a new lock.",
      "henceforth.",
    ],
    video: { mp4: "/learn/the-transaction/episode.mp4" },
  },
  {
    number: 13,
    slug: "fees-and-change",
    title: "Fees and change",
    dek: "Every payment splits in three — to mum, back to you, to the miner. The fee prices bytes, not value: postage, in pennies.",
    published: true,
    durationSec: 102,
    music: { season: "Handel", piece: "Water Music · Bourrée (United States Marine Band, public domain)" },
    concepts: [
      "Every payment splits three ways: the recipient, your change, and the miner's fee.",
      "The fee prices the size of the payment, not its value — a million pounds posts for the same pennies.",
      "Genesis brought op_mul back: bitcoin script can multiply, and counting money needs times tables.",
      "The season's first live network read: the price lands on the stack, one number, ready to count with.",
    ],
    // Curated to commands that run on a fresh install — lesson narration words
    // (fee-intro, split-three, fee-bytes, fee-close) are excluded; a new app
    // hasn't defined them.
    codeAlong: [
      "1000 800 - .",
      "50 tx-set-fee",
      "2 3 * .",
      "price",
      ".",
    ],
    transcript: [
      "when i pay mum... who pays for the ride?",
      "episode thirteen. fees and change.",
      "every payment splits in three.",
      "so what happens to the rest of my coin?",
      "you pay mum 800.",
      "but the coin you pay with is worth 1000.",
      "800 goes to mum.",
      "the rest comes back to you - almost.",
      "let's count it.",
      "two hundred back. almost - watch the almost.",
      "the missing part is the fee.",
      "it pays the miner who carries the payment.",
      "and it prices the size - not the value.",
      "a million pounds posts for the same pennies.",
      "we set ours like this.",
      "fifty satoshis for a thousand bytes. postage, in pennies.",
      "counting money needs times tables too.",
      "six. bitcoin script can do this too - genesis brought op_mul back.",
      "and what is a whole coin worth today? let's ask.",
      "live, from the market. our first read from the network.",
      "the same price in pennies - on the stack, ready to count with.",
      "to mum. back to you. to the miner.",
      "every payment, three ways.",
      "and every satoshi accounted for.",
      "henceforth.",
    ],
    video: { mp4: "/learn/fees-and-change/episode.mp4" },
  },
  {
    number: 14,
    slug: "signatures",
    title: "Signatures",
    dek: "A signature is a claim only a key can make, and anyone can check. Change one character and the claim is dead; a payment is the same mathematics.",
    published: true,
    durationSec: 124,
    music: { season: "Handel", piece: "Water Music · Lentement (United States Marine Band, public domain)" },
    concepts: [
      "A signature is a claim only a key can make, and anyone can check it without the key.",
      "Verification is exact: change one character of the message and the claim is dead.",
      "The address is the public half; the key that made the signature never travels.",
      "A payment is a signed message whose message is the transaction, and op_checksig is the same check.",
    ],
    // Curated to commands that run on a fresh install — lesson narration words
    // (sig-intro, sig-claim, sig-bridge, sig-close) are excluded; a new app
    // hasn't defined them. The message was signed with a throwaway key made
    // for the episode and discarded; nothing here needs a wallet.
    codeAlong: [
      "verify-msg 15QrsxL3RfpX9kVC9WXpFp9HhXGZjFrBuw INTO/HNQJs7JMiJvxrLLAL6+lfQPSY9vjQRlaaWGkO0IH/z8TkDQPXbDFqS4+6SmJ0f4ZFzJPWddC8NFjzH3IVA= i am henceforth",
      ".",
      "verify-msg 15QrsxL3RfpX9kVC9WXpFp9HhXGZjFrBuw INTO/HNQJs7JMiJvxrLLAL6+lfQPSY9vjQRlaaWGkO0IH/z8TkDQPXbDFqS4+6SmJ0f4ZFzJPWddC8NFjzH3IVA= i am hencef0rth",
      ".",
      "checksig-fixture",
      "op_checksig",
    ],
    transcript: [
      "how do you prove it's yours?",
      "episode fourteen. signatures.",
      "a signature is a claim only one secret can make.",
      "and anyone can check it.",
      "i signed a message earlier. with a key. here it is.",
      "the message: i am henceforth",
      "the address: 15QrsxL3RfpX9kVC9WXpFp9HhXGZjFrBuw",
      "the signature: INTO/HNQJs7JMiJvxrLLAL6+lfQPSY9vjQRlaaWGkO0IH/z8TkDQPXbDFqS4+6SmJ0f4ZFzJPWddC8NFjzH3IVA=",
      "the secret stays home. the signature travels.",
      "three things. the words, the address, and the claim.",
      "you don't need my key to check it. nobody does.",
      "valid. the key behind that address made this.",
      "minus one is yes.",
      "now i change one letter of the message. a zero for an o.",
      "invalid. one character, and the claim is dead.",
      "zero is no.",
      "a payment is a signed message too.",
      "the message is the transaction.",
      "and the check is op_checksig.",
      "remember the finale? a signed payment, ready to check.",
      "the signature and the key are on the stack. now the check.",
      "the same yes. a message or a payment. one mathematics.",
      "only the secret can make it.",
      "anyone can check it.",
      "that is what yours means.",
      "henceforth.",
    ],
    video: { mp4: "/learn/signatures/episode.mp4" },
  },
];

const byNumber = [...episodes].sort((a, b) => a.number - b.number);

export function publishedEpisodes(): Episode[] {
  return byNumber.filter((e) => e.published);
}

export function getEpisode(slug: string): Episode | undefined {
  return episodes.find((e) => e.slug === slug);
}

// Neighbours by episode number across ALL episodes, so the page can tease an
// unpublished "next … soon". The page decides whether to link based on .published.
export function adjacentEpisodes(slug: string): { prev?: Episode; next?: Episode } {
  const i = byNumber.findIndex((e) => e.slug === slug);
  if (i === -1) return {};
  return { prev: byNumber[i - 1], next: byNumber[i + 1] };
}

export function formatDuration(sec?: number): string | undefined {
  if (!sec) return undefined;
  const m = Math.floor(sec / 60);
  const s = Math.round(sec % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}
